// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxdsNSvmlLT_63fI3khVlCpXoGj27qKbg',
    appId: '1:45146094155:android:3dc19e84cfcf58d75febce',
    messagingSenderId: '45146094155',
    projectId: 'we-chat-6992a',
    storageBucket: 'we-chat-6992a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwJNdqKTKfDSu145j2CAMSH_GDvqre4g4',
    appId: '1:45146094155:ios:d3f5a43b6a08a5b25febce',
    messagingSenderId: '45146094155',
    projectId: 'we-chat-6992a',
    storageBucket: 'we-chat-6992a.appspot.com',
    androidClientId: '45146094155-h50q062nokrb2bnjgcdel74si49o68km.apps.googleusercontent.com',
    iosClientId: '45146094155-c8q1imfpe2eckuf40fkn5m8nttq4sg0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmZdwfIUrMjeH71fcJrmxQ7fpM4UJLVk8',
    appId: '1:45146094155:web:c2d12f6bd4ef90625febce',
    messagingSenderId: '45146094155',
    projectId: 'we-chat-6992a',
    authDomain: 'we-chat-6992a.firebaseapp.com',
    storageBucket: 'we-chat-6992a.appspot.com',
  );

}